# Numpy

In [8]:
import numpy as np

In [4]:
a = np.arange(10000)
l = list(range(10000))

In [5]:
%timeit for i in range(100): a1 = a*2

726 µs ± 3.52 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [6]:
%timeit for i in range(100): l1 = l*2

4.81 ms ± 27.8 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [8]:
a = np.arange(5)
a*2

array([0, 2, 4, 6, 8])

In [20]:
data = [[1,2,3,4,5],[1,2,5,6,9]]
a1 = np.array(data)
a1

array([[1, 2, 3, 4, 5],
       [1, 2, 5, 6, 9]])

In [13]:
type(a1)

numpy.ndarray

In [21]:
a1.shape

(2, 5)

In [22]:
a1.dtype

dtype('int32')

In [23]:
a1.ndim

2

In [24]:
a1 = np.arange(10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
a1.dtype

dtype('int32')

In [33]:
a1.astype('float64')

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [34]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [35]:
np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [36]:
np.eye(3,3) # identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
np.full((3,3), fill_value = 5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [38]:
np.empty((3,3)) #whatever finds quickly is filed in this empty array

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Arithmatic operations

In [40]:
a1 = np.arange(6)
a1

array([0, 1, 2, 3, 4, 5])

In [41]:
a1 + 2

array([2, 3, 4, 5, 6, 7])

In [42]:
a1 + a1

array([ 0,  2,  4,  6,  8, 10])

In [43]:
a1*3

array([ 0,  3,  6,  9, 12, 15])

In [44]:
a1 // 2

array([0, 0, 1, 1, 2, 2], dtype=int32)

In [45]:
6 / a1 # here every element in a1 divides 6

C:\Users\prana\AppData\Local\Temp/ipykernel_348/2813095428.py:1: RuntimeWarning: divide by zero encountered in true_divide
  6 / a1


array([inf, 6. , 3. , 2. , 1.5, 1.2])

In [46]:
a1**2

array([ 0,  1,  4,  9, 16, 25], dtype=int32)

In [47]:
a1*a1

array([ 0,  1,  4,  9, 16, 25])

In [48]:
a1**a1

array([   1,    1,    4,   27,  256, 3125], dtype=int32)

In [49]:
a1 = np.array([21,4,5,3,6])
a2 = np.array([43,5,2,7,8])

In [50]:
a1>a2

array([False, False,  True, False, False])

In [51]:
a1<a2

array([ True,  True, False,  True,  True])

### Indexing and slicing

In [53]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
a[3]

3

In [55]:
a[-4]

6

In [58]:
a[3:7]

array([3, 4, 5, 6])

In [57]:
a[1:]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
a2 = np.arange(11)
a2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
a2[:3] = 13
a2

array([13, 13, 13,  3,  4,  5,  6,  7,  8,  9, 10])

In [63]:
a2[:] = 12
a2

array([12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12])

In [66]:
a1 = np.array(10)
c1 = a1.copy()
c1

array(10)

In [90]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [69]:
a.shape

(16,)

In [70]:
a1 = a.reshape((16,1))
a1.shape

(16, 1)

In [72]:
a1.ndim

2

In [79]:
a1 = a.reshape((4,4))

In [80]:
np.dot(a1,a1.T)

array([[ 14,  38,  62,  86],
       [ 38, 126, 214, 302],
       [ 62, 214, 366, 518],
       [ 86, 302, 518, 734]])

In [81]:
a1.T

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [91]:
a.sort()
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
np.square(a)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

In [93]:
np.sqrt(a)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [94]:
np.abs([-1,-3,-5,-4])

array([1, 3, 5, 4])

In [95]:
a1 = np.array([2,3,4,7,5,8])
a2 = np.array([8,7,2,0,5,9])
np.maximum(a1,a2)

array([8, 7, 4, 7, 5, 9])

In [96]:
np.minimum(a1,a2)

array([2, 3, 2, 0, 5, 8])

In [97]:
np.power(a1,a2)

array([      256,      2187,        16,         1,      3125, 134217728],
      dtype=int32)

In [98]:
np.greater(a1,a2)

array([False, False,  True,  True, False, False])

In [99]:
np.less(a1,a2)

array([ True,  True, False, False, False,  True])

In [100]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [102]:
a.mean()

4.5

In [103]:
a.sum()

45

In [104]:
a.max()

9

In [105]:
a.min()

0

In [107]:
a.std()

2.8722813232690143

In [108]:
a.var()

8.25

In [109]:
a.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [110]:
a.cumprod()

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [111]:
np.median(a)

4.5

In [112]:
a = np.arange(25)
a = a.reshape((5,5))
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [114]:
a.mean(axis = 1)#axia 1 means along the row

array([ 2.,  7., 12., 17., 22.])

In [115]:
a.mean(axis = 0) #axis 0 means along the column

array([10., 11., 12., 13., 14.])

In [116]:
a.var(axis = 1)

array([2., 2., 2., 2., 2.])

In [117]:
a.dot(a.T)

array([[  30,   80,  130,  180,  230],
       [  80,  255,  430,  605,  780],
       [ 130,  430,  730, 1030, 1330],
       [ 180,  605, 1030, 1455, 1880],
       [ 230,  780, 1330, 1880, 2430]])

In [6]:
from numpy.linalg import det, inv, eig

In [10]:
a = np.array([4,6,7,8,4,6,8,9,7]).reshape((3,3))
a

array([[4, 6, 7],
       [8, 4, 6],
       [8, 9, 7]])

In [11]:
det(a)#determinant

127.99999999999997

In [12]:
inv(a)#inverse

array([[-0.203125 ,  0.1640625,  0.0625   ],
       [-0.0625   , -0.21875  ,  0.25     ],
       [ 0.3125   ,  0.09375  , -0.25     ]])

In [123]:
eig(a)#eigen 

(array([19.69625748+0.j        , -2.34812874+0.99246559j,
        -2.34812874-0.99246559j]),
 array([[-0.50577472+0.j        ,  0.21821534-0.34731668j,
          0.21821534+0.34731668j],
        [-0.52069669+0.j        , -0.70840036+0.j        ,
         -0.70840036-0.j        ],
        [-0.68779859+0.j        ,  0.45854899+0.34591175j,
          0.45854899-0.34591175j]]))

In [13]:
np.concatenate((a,a.T), axis =1)

array([[4, 6, 7, 4, 8, 8],
       [8, 4, 6, 6, 4, 9],
       [8, 9, 7, 7, 6, 7]])

# Pandas